spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: loclhost:9092
    security-protocol: SSL
    ssl:
      keystore-location: /Users/z083387/Desktop/Kafka/Self-signed/dam-publish-dev.target.com.jks
      truststore-location: /Users/z083387/Desktop/Kafka/Self-signed/dev.server.keystore.jks
      truststore-password: kafkasecret
      keystore-password: kafkasecret
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: com.tgt.mkt.cam.entity.types.CustomPostgreSqlDialect
jwt:
  header: Authorization
  jti: 69171853-0314-40fa-9dbd-91e89ef3c952
  secret: secret
  expiry: 2
token:
  prefix: Bearer
hazelcast:
  host: localhost
  port: 5701
  name: hz-compose
  password: test@user
