endpoints:
  enabled: true
  refresh:
    enabled: true
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
spring:
  kafka:
    bootstrap-servers: 10.65.133.232:9093
    security-protocol: SSL
    ssl:
      #keystore-password: dam_Certificate1234
      #keystore-location: /Users/z083387/Desktop/Kafka/kafka-dev/dam-publish-dev.target.com.jks
      #truststore-location: /Users/z083387/Desktop/Kafka/kafka-dev/kafka.dev.client.truststore.jks
      #truststore-password: changeit
      keystore-location: /Users/z083387/Desktop/Kafka/Self-signed/dam-publish-dev.target.com.jks
      truststore-location: /Users/z083387/Desktop/Kafka/Self-signed/dev.server.keystore.jks
      truststore-password: kafkasecret
      keystore-password: kafkasecret
    consumer:
      bootstrap-servers: 10.65.133.232:9093
    producer:
      bootstrap-servers: 10.65.133.232:9093
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: com.tgt.mkt.cam.entity.CustomPostgreSqlDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  header: Authorization
  jti: 69171853-0314-40fa-9dbd-91e89ef3c952
  secret: secret
  expiry: 2
token:
  prefix: Bearer
